#!/usr/bin/env bun
/**
 * `bun scripts/live/report.ts <run-dir>`: the e2e report (Markdown, to stdout) from what
 * scripts/live/e2e.sh recorded in <run-dir>: `steps.tsv` (`id<TAB>status<TAB>title`, one
 * line per step, in order), `steps/<id>.txt` (the step's evidence: commands, their output,
 * one `==> PASS`/`FAIL`/`SKIP` line per expectation) and `meta.txt` (`key: value` lines: date,
 * versions, images). The evidence files are committed next to the report.
 */
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

export type Status = "PASS" | "FAIL" | "SKIP";

/** One recorded step. */
export interface StepRecord {
  readonly id: string;
  readonly status: Status;
  readonly title: string;
}

const STATUSES: readonly string[] = ["PASS", "FAIL", "SKIP"];

/** Parses `steps.tsv`; malformed lines are skipped. */
export function parseSteps(tsv: string): StepRecord[] {
  return tsv.split("\n").flatMap((line) => {
    const [id, status, ...title] = line.split("\t");
    if (id === undefined || id === "" || status === undefined || !STATUSES.includes(status)) {
      return [];
    }
    return [{ id, status: status as Status, title: title.join("\t") }];
  });
}

/** `key: value` lines. */
export function parseMeta(text: string): Array<[string, string]> {
  return text.split("\n").flatMap((line) => {
    const at = line.indexOf(": ");
    return at <= 0 ? [] : [[line.slice(0, at), line.slice(at + 2)] as [string, string]];
  });
}

/** An expectation line of an evidence file (distinct from any command's own PASS/FAIL). */
const MARKER = /^==> (PASS|FAIL|SKIP) /;

/** The expectation lines of an evidence file, marker removed (the table's last column). */
export function verdictLines(evidence: string): string[] {
  return evidence
    .split("\n")
    .filter((l) => MARKER.test(l))
    .map((l) => l.slice(4));
}

function cell(text: string): string {
  return text.replace(/\|/g, "\\|").replace(/`/g, "'");
}

const ICON: Readonly<Record<Status, string>> = { PASS: "PASS", FAIL: "**FAIL**", SKIP: "SKIP" };
/** How much of a failed step's evidence the report quotes (the file has all of it). */
const FAILURE_LINES = 40;

/** The whole report. `evidence(id)` returns a step's evidence text ("" when none). */
export function renderReport(
  steps: readonly StepRecord[],
  meta: ReadonlyArray<readonly [string, string]>,
  evidence: (id: string) => string,
): string {
  const count = (s: Status) => steps.filter((x) => x.status === s).length;
  const lines = [
    "# jev-cops live end-to-end report (Docker)",
    "",
    "Generated by `scripts/live/e2e.sh` (D-115: every harness ran inside a container on an",
    "internal network, against the fake model API, with dummy keys). Each step's full evidence",
    "(commands and their output) is in [`e2e/steps/<id>.txt`](./e2e/steps/).",
    "",
    `**${count("PASS")} passed · ${count("FAIL")} failed · ${count("SKIP")} skipped** (${steps.length} steps)`,
    "",
    ...meta.map(([k, v]) => `- ${k}: ${v}`),
    "",
    "| Step | Result | What | Expectations |",
    "|---|---|---|---|",
  ];
  for (const s of steps) {
    const checks = verdictLines(evidence(s.id)).map(cell).join("<br>");
    lines.push(
      `| [${s.id}](./e2e/steps/${s.id}.txt) | ${ICON[s.status]} | ${cell(s.title)} | ${checks} |`,
    );
  }
  const failed = steps.filter((s) => s.status === "FAIL");
  if (failed.length > 0) {
    lines.push("", "## Failures", "");
    for (const s of failed) {
      const tail = evidence(s.id).trimEnd().split("\n").slice(-FAILURE_LINES).join("\n");
      lines.push(
        `### ${s.id} ${s.title}`,
        "",
        `Last lines of [the evidence](./e2e/steps/${s.id}.txt):`,
        "",
        "```text",
        tail,
        "```",
        "",
      );
    }
  }
  return `${lines.join("\n").trimEnd()}\n`;
}

/** Reads a run directory and renders its report. */
export function reportFor(dir: string): string {
  const read = (p: string) => (existsSync(p) ? readFileSync(p, "utf8") : "");
  return renderReport(
    parseSteps(read(join(dir, "steps.tsv"))),
    parseMeta(read(join(dir, "meta.txt"))),
    (id) => read(join(dir, "steps", `${id}.txt`)),
  );
}

/** The command line; returns the exit code. */
export function runReportCli(argv: readonly string[], write: (fd: 1 | 2, t: string) => void) {
  const dir = argv[0];
  if (dir === undefined) {
    write(2, "usage: bun scripts/live/report.ts <run-dir>\n");
    return 2;
  }
  write(1, reportFor(dir));
  return 0;
}

if (import.meta.main) {
  const write = (fd: 1 | 2, t: string) => (fd === 1 ? process.stdout : process.stderr).write(t);
  process.exit(runReportCli(process.argv.slice(2), write));
}
